---
title: "Review of covidham Shiny Package"
description: |
  In this article explains I will be reviewing Soban's shiny package made for Assignment 2 of ETC5523
author:
  - name: Vinny Vu
    affiliation: Master's Student at Monash University
date: 10-24-2020
output:
  distill::distill_article:
    self_contained: false
bibliography: mybib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

# Introduction 

In this blog post I will be reviewing Soban's R package "covidham" made for Assignment 2 of ETC5523 contain coronavirus data, functions and shiny application. This package can be found via Github [here](https://github.com/etc5523-2020/r-package-assessment-msobanq) [@GIT]. Further, the pkgdown site can be found [here](https://etc5523-2020.github.io/r-package-assessment-msobanq/) [@Pkgdown]. The shiny application contained in the package analysis the state of coronavirus in most Aisan countries being "the most densely populated continent and the origin of the pandemic." 

The application contains a plot of Stringency Index (the level of emergency declared and the level of precautions taken by government.) This variable is scaled from 0-100 (100 = strictest.) Further, a scatter plot has been included comparing 3 coronavirus related variables at once across Asian countries (1 variable on the x-axis, 1 on the y-axis and the last variable being the size and colour of the point.) Some variables that can be plotted include, total cases, total deaths, population and more. All variables included can be viewed through the `covid_data` used to create the package. data tables have been included also showing the total cases, new cases, total deaths, new deaths of specific Asian countries at a particular date.

# What did I think this package would do? Did it do it?

At the onset of viewing the github page the readme file provides a clear picture of what the shiny application includes having the introduction slide of the package explaining what is included in the application. The introduction highlights the stringency index plot, 3 variables scatter plot and summary data table. Further, the readme includes descriptions of both the stringency and launch_app functions. The Covid World Data vignette included provides a visualization of the data sets and again explains the functions. However, the interact function has not be included and users would have to go to the reference tab to explore this function. 

As described in the help file and vignette, I was successfully able to use the covid_data function to obtain the data used in the application and stringency() function the create the stringency plot used in the Shiny application. The applicaiton explores the state of coronavirus in Asia having 3 main tabs which include the stringency index line graph, 3 variables scatter plot and summary data table.  

# Are the improvements that could be made to the code? 

I ran into issues using the launch_app() having trouble locating the the shiny app even after reinstallation. After assessing the code I was unable to find the issue. I think to further improve on the stringency function in the package having an input to select specific countries for plotting rather than selecting all countries can be useful to allow users to manipulate what countries to plot. I came into some issues around use of the stringency only being able to use the function after loading dplyr and ggplot2. I believe has come as functions in dplyr and ggplot2 have been used in the function however, they the function have not been explicitly refered to or imported in the namespace. I would suggest to either reference the function for example `dplyr::filter()` or use `@importFrom magrittr %>%` in the description. 

# Are there improvements that could be made to the shiny app inside the package? 

The format of the shiny application is very aesthetic and easy to follow highlighted by the styling in the plots and data tables included. Some improvements I would make to the Stringency index line graph would be to change the label of the y-axis to read "stringency Index" and removing the x-axis label as it is clear date is being plotted. In the 3 variables plot, to improve comparability between the size of the points the legend could be arrange by point size rather than alphabetical order. Further, renaming the variables to excluded any underscores would provide a cleaner look. Lastly, in the data table, column names should remove the underscores and capitalise the first letters. Numbers should also include commas to improve readability of the values.     

# Is the documents sufficient to get started? 

The overall package documentation provides a succinct summary of what is included in the package. The documentation of the launch_app function is clear and easy to understand. I had trouble understanding the documentation for the stringency function however. Elaboring on what is being plotting in the stringency function could be included as users will not know what the function does until running the application. Further, the `input` argument description is a bit vague, this argument can be left out as there is actually no argument needed to run the function. Providing an example for the interact function could be included to better help users understand how to use the function.      

# Summary 

Overall, Soban's package and shiny application provided an interesting and insightful take on the state of coronavirus in Asia. From the Stringency Index plot it was interesting to see how early many Asian countries have reacted early to coronavirus reaching high levels of emergency declaration as early as February. Several countries even reach a 100 index level, whereas several countries have managed to maintain low levels of stringency through early action.  

# Appendix 

#### Documentation

The package includes all the following forms of documentation:

- [ $\checkmark$ ] **Installation instructions:** for the package is found in README  
- [ $\checkmark$ ] **Vignette(s)** demonstrating major functionality that runs successfully locally  
- [ $\checkmark$ ] **Function Documentation:** for all exported functions in R help  
- [ ] **Examples** for all exported functions in R Help that run successfully locally  

#### Functionality

- [ $\checkmark$ ] **Installation:** Installation succeeds as documented.  
- [ $\checkmark$ ] **Functionality:** Any functional claims of the software been confirmed.  
- [ $\checkmark$ ] **Automated tests:** Unit tests cover essential functions of the package  
and a reasonable range of inputs and conditions. All tests pass on the local machine.  

- The readme provides clear instructions to install and use the package 
- Vignettes provides a clear overview of the package. 
- Function documentation for all functions are included 
- Examples could be included in function documentation to use as reference

#### Comments

- Installation succeeded with no issues 
- Functions in the package work however, only after loading servaral other dependency packages 
- Both function test ran without failing


This blog post as been made through Distill [@distill]

