---
title: "Current State of Coronavirus Cases in The Netherlands"
description: |
  This article assesses the current state of conronavirus cases in The Netherlands as at 31th July 2020
author:
  - name: Vinny Vu
    affiliation: Master's Student at Monash University
date: 08-31-2020
output:
  distill::distill_article:
    self_contained: false
bibliography: mybib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

```{r, include=FALSE}
library(coronavirus)
library(tidyverse)
library(plotly)
library(lubridate)
library(kableExtra)
```

```{r coronavirus_data }
data("coronavirus")
covid19_Neth <- coronavirus %>%
  filter(country == "Netherlands") %>%
  arrange(date) %>%
  filter(date >= "2020-02-27")

```


```{r}
head(covid19_Neth) %>% kable() %>% kable_styling()
```

```{r}
covid19_Neth %>%
  select(date,type,cases) %>%
  group_by(date,type) %>%
  summarise(cases = sum(cases)) %>%
  ggplot(aes(x = date,
             y = cases,
             color = type)) +
  geom_line()
```

```{r}
covid19_Neth_cum <- covid19_Neth %>%
  select(date,type,cases) %>%
  group_by(date,type) %>%
  summarise(cases = sum(cases)) %>%
  pivot_wider(names_from = type,
              values_from = cases) %>%
  ungroup() %>%
  mutate(`total cases` = cumsum(confirmed),
         `total deaths` = cumsum(death)) 
```
```{r}
cum_plot <- covid19_Neth_cum %>%
  ggplot(aes(x = date, y = `total cases`)) +
  geom_line(fill = "blue")

ggplotly(cum_plot)
```

